version: '3'

networks:
  localdev:
    name: localdev
    
services:
  main-api:
    build: ./
    restart: always
    ports:
      - 7000:80
    depends_on:
      - db-mysql
    networks:
      - localdev
        
  db-mysql:
    image: mysql
    container_name: db-mysql
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:'Abc.123'
    ports:
      - 3306:3306
    networks:
      - localdev
